### ISSUE TITLE
Styles on body interfere when used in other app

### ISSUE THREAD

**Issue by indacloud** [blackjk3/react-signature-pad#7]
Some styles are only relevant for the example and break styling when used in an actual app.
I moved the styles to index.html.

I added a pull request https://github.com/blackjk3/react-signature-pad/pull/6

Thanks

**Comment by agilgur5** [comment]
I was similarly annoyed by the irrelevant styles and unneeded divs used here. Seeing as your PR still hasn't been merged, I eventually just made my own fork https://github.com/agilgur5/react-signature-canvas and NPM package that does away with all of them and adds a bunch more documentation (plus adds a trim features and allows you to pass any props to the underlying canvas element)
